# Generated by Django 3.2.7 on 2021-09-09 16:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('code', models.CharField(max_length=3, verbose_name='Code')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Text')),
                ('translation', models.CharField(max_length=300, verbose_name='Translation')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('learning_index', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.language')),
            ],
        ),
    ]
